timeout: 0
verbose: yes

/FrostyOS
    protocol: limine
    path: boot():/FrostyOS/kernel.elf
    module_path: boot():/FrostyOS/ksymbols.map
    module_path: boot():/FrostyOS/initramfs.tar
    resolution: 1920x1080x32
